### ISSUE TITLE
Problems when inference

### ISSUE THREAD

**Issue by yahooo-m** [jimmy-dq/DropSeg#1]
Hi, I want to use the inference code to generate davis results. But i got a problem: 
AssertionError: Input image height (480) doesn't match model (224), which is shown in the self.patch_embed of models_vit.
Can you help me?

**Comment by jimmy-dq** [comment]
@yahooo-m Hi, this is because the default image size constraint (224) in the 3rd party timm package. Just edit the vision_transformer.py (L164) of timm and comment the `assert` code lines.

**Comment by yahooo-m** [comment]
Thanks!
